# Loading Dataset

In [2]:
import pandas as pd

In [3]:
prod = pd.read_csv(r"C:\Users\user\Downloads\Omnichannel retail inventory dataset\omni_products.csv")

ord = pd.read_csv(r"C:\Users\user\Downloads\Omnichannel retail inventory dataset\omni_orders.csv")

cust = pd.read_csv(r"C:\Users\user\Downloads\Omnichannel retail inventory dataset\omni_customers.csv")

ord_it = pd.read_csv(r"C:\Users\user\Downloads\Omnichannel retail inventory dataset\omni_order_items.csv")

inv = pd.read_csv(r"C:\Users\user\Downloads\Omnichannel retail inventory dataset\omni_inventory.csv")

inv_move = pd.read_csv(r"C:\Users\user\Downloads\Omnichannel retail inventory dataset\omni_inventory_movements.csv")

stor = pd.read_csv(r"C:\Users\user\Downloads\Omnichannel retail inventory dataset\omni_stores.csv")

ware = pd.read_csv(r"C:\Users\user\Downloads\Omnichannel retail inventory dataset\omni_warehouses.csv")

# Understanding dataset

## Customers Table

In [ ]:
print("Initial Shape:", cust.shape)

In [4]:
cust.head()

  customer_id  customer_name       city signup_date
0   CUST00000    Arjun Mehta     Mumbai  2023-01-05
1   CUST00001    Wei Johnson    Chennai  2023-09-13
2   CUST00002     Chen Patel  Bangalore  2023-03-18
3   CUST00003  Olivia Kovacs       Pune  2023-07-12
4   CUST00004    Emma Kovacs    Chennai  2022-02-06

In [5]:
cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5000 non-null   object
 1   customer_name  5000 non-null   object
 2   city           5000 non-null   object
 3   signup_date    5000 non-null   object
dtypes: object(4)
memory usage: 156.4+ KB

In [6]:
cust.isnull().sum()

customer_id      0
customer_name    0
city             0
signup_date      0
dtype: int64

In [7]:
cust['customer_id'].nunique()

5000

In [ ]:
cust['customer_id'].nunique() == len(cust)

### Notes:
- All unique customer_ID. perfect for primary key constraint. 
- Signup date dtype is object which needs to be corrected.

## Date format correction

In [ ]:
cust['Signup_Date'] = pd.to_datetime(cust['Signup_Date'], errors='coerce')
cust.info()

In [ ]:
cust['Signup_Date'] # converted to datetime format successfully.

## Products Table

In [ ]:
print("Initial Shape:", prod.shape)

In [8]:
prod.head()

  product_id product_name     category brand    price
0  PROD00000  Dell Item_0       Sports  Dell  1888.71
1  PROD00001  Sony Item_1  Electronics  Sony  1480.04
2  PROD00002    HP Item_2  Electronics    HP   982.42
3  PROD00003  Dell Item_3  Electronics  Dell   144.96
4  PROD00004  Puma Item_4  Electronics  Puma   533.58

In [9]:
prod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    800 non-null    object
 1   product_name  800 non-null    object
 2   category      800 non-null    object
 3   brand         800 non-null    object
 4   price         800 non-null    float64
dtypes: float64(1), object(4)
memory usage: 31.4+ KB

In [10]:
prod.isnull().sum()

product_id      0
product_name    0
category        0
brand           0
price           0
dtype: int64

In [11]:
# brand consistency check - if any brand repeat.

prod['brand'].value_counts()

brand
H&M          69
Sony         67
Dell         66
Noise        62
Samsung      61
Puma         60
Decathlon    58
Nike         57
Boat         56
HP           54
Zara         52
Ikea         49
Apple        47
Adidas       42
Name: count, dtype: int64

In [12]:
prod['category'].unique()

array(['Sports', 'Electronics', 'Home', 'Fashion'], dtype=object)

## Removing Invalid Values

In [ ]:
prod = prod[prod['price'] > 0]

# Order Table

In [ ]:
print("Initial Shape:", ord.shape)

(50000, 6)

In [ ]:
ord.head(10)

     order_id customer_id  order_date channel  store_id order_status
0  ORD0000000   CUST03080  2024-09-06   Store  STORE038     Returned
1  ORD0000001   CUST00191  2023-06-01   Store  STORE009    Cancelled
2  ORD0000002   CUST02367  2024-04-13   Store  STORE029    Cancelled
3  ORD0000003   CUST03515  2024-09-05  Online       NaN    Delivered
4  ORD0000004   CUST00780  2024-04-16   Store  STORE004    Delivered

In [15]:
ord.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      50000 non-null  object
 1   customer_id   50000 non-null  object
 2   order_date    50000 non-null  object
 3   channel       50000 non-null  object
 4   store_id      16715 non-null  object
 5   order_status  50000 non-null  object
dtypes: object(6)
memory usage: 2.3+ MB

In [16]:
ord.isnull().sum()

order_id            0
customer_id         0
order_date          0
channel             0
store_id        33285
order_status        0
dtype: int64

In [17]:
ord[ord.duplicated(keep=False)]

Empty DataFrame
Columns: [order_id, customer_id, order_date, channel, store_id, order_status]
Index: []

In [18]:
ord.duplicated().sum()

0

In [19]:
ord['channel'].value_counts()

channel
Store     16715
App       16654
Online    16631
Name: count, dtype: int64

In [20]:
ord['order_status'].value_counts()

order_status
Shipped      12599
Returned     12583
Cancelled    12562
Delivered    12256
Name: count, dtype: int64

In [ ]:
ord['order_id'].nunique() == len(ord)

### Notes:
- No duplicates found.
- order_date dtype is wrong.
- Nan value is present in store_id. Is likely because of non-store orders.

## Order_Date Format Correction

In [ ]:
ord['Order_Date'] = pd.to_datetime(ord['Order_Date'], errors='coerce')
ord.info()

## Store Null Value Handling

In [ ]:
mask = (ord['Channel'].isin(['Online', 'App'])) & (ord['Store_Id'].isna())
ord.loc[mask, 'Store_Id'] = 'ONLINE'
ord.head(15)

In [ ]:
# Null Value Checked
ord.isnull().sum()

# After Correction Notes:
- Order_Date converted to date format. 
- Null value in Store_Id indeed null as channel for App and Online is not exist. So NaN in Store_Id filled by following rule: if NaN and Channel value is 'App' or 'Online', filled with 'ONLINE'.

## Order Items Table

In [ ]:
print("Initial Shape:", ord_it.shape)

(149958, 4)

In [22]:
ord_it.head()

   order_item_id    order_id product_id  quantity
0              1  ORD0000000  PROD00502         3
1              2  ORD0000000  PROD00666         4
2              3  ORD0000000  PROD00159         3
3              4  ORD0000000  PROD00777         1
4              5  ORD0000001  PROD00658         4

In [23]:
ord_it.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149958 entries, 0 to 149957
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_item_id  149958 non-null  int64
 1   order_id       149958 non-null  object
 2   product_id     149958 non-null  object
 3   quantity       149958 non-null  int64
dtypes: int64(2), object(2)
memory usage: 4.6+ MB

In [24]:
ord_it.isnull().sum()

order_item_id    0
order_id         0
product_id       0
quantity         0
dtype: int64

In [25]:
ord_it['order_id'].nunique()

50000

In [26]:
ord_it['quantity'].describe()

count    149958.000000
mean          2.501740
std           1.117082
min           1.000000
25%           2.000000
50%           3.000000
75%           3.000000
max           4.000000
Name: quantity, dtype: float64

### Notes:
- Only 50K order item's unique. Because of many order's in one.
- likely no invalid quantity.

## Removing Invalid Values

In [ ]:
ord_it = ord_it[ord_it['quantity'] > 0]

### Inventory Table

In [ ]:
print("Initial Shape:",inv.shape)

(8000, 4)

In [28]:
inv.head()

  product_id warehouse_id  stock_quantity last_updated
0  PROD00000        WH000             263   2026-04-13
1  PROD00000        WH001             565   2026-04-13
2  PROD00000        WH002             284   2026-04-13
3  PROD00000        WH003              20   2026-04-13
4  PROD00000        WH004             203   2026-04-13

In [29]:
inv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      8000 non-null   object
 1   warehouse_id    8000 non-null   object
 2   stock_quantity  8000 non-null   int64
 3   last_updated    8000 non-null   object
dtypes: int64(1), object(3)
memory usage: 250.1+ KB

In [30]:
inv.isnull().sum()

product_id        0
warehouse_id      0
stock_quantity    0
last_updated      0
dtype: int64

In [31]:
# stock check in each warehouse
inv.groupby('warehouse_id')['stock_quantity'].sum()

warehouse_id
WH000    389718
WH001    402664
WH002    397092
WH003    406724
WH004    392143
WH005    412841
WH006    407051
WH007    392828
WH008    394715
WH009    408924
Name: stock_quantity, dtype: int64

### Notes:
- last updated dtype is wrong.

## Last_Updated date format correction:

In [ ]:
inv['Last_Updated'] = pd.to_datetime(inv['Last_Updated'], errors='coerce')
inv.info()

## Inventory Movement Table

In [ ]:

print("Initial Shape:" inv_move.shape)

(100000, 5)

In [33]:
inv_move.head()

  product_id warehouse_id  change_qty   reason        date
0  PROD00578        WH005         -44  Restock  2024-04-30
1  PROD00704        WH006          82  Restock  2023-01-16
2  PROD00453        WH005           0  Restock  2023-07-20
3  PROD00702        WH007          52     Sale  2023-10-17
4  PROD00119        WH009          47     Sale  2024-10-22

In [34]:
inv_move.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   product_id    100000 non-null  object
 1   warehouse_id  100000 non-null  object
 2   change_qty    100000 non-null  int64
 3   reason        100000 non-null  object
 4   date          100000 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [35]:
# Whitespace check:
(inv_move == "").sum()

product_id      0
warehouse_id    0
change_qty      0
reason          0
date            0
dtype: int64

In [36]:
inv_move['reason'].value_counts()

reason
Sale       33538
Restock    33246
Return     33216
Name: count, dtype: int64

### Notes:
- date dtype is wrong.
- Restock: stock comes IN, must be positive. Needs transformation.
- Sale: stock goes OUT, must be negative. Needs transformation.

In [ ]:
# Date format correction:

inv_move['Date'] = pd.to_datetime(inv_move['Date'], errors='coerce')
inv_move.info()

In [ ]:
# table check
inv_move.head(15)

In [ ]:
# Numpy Imported

import numpy as np

In [ ]:
mask2 = inv_move['Reason'].isin(['Restock', 'Return'])
inv_move['Change_Qty'] = np.where(mask2, inv_move['Change_Qty'].abs(),
                                  -inv_move['Change_Qty'].abs()
                                  )
inv_move.head(15)

## After Correction Notes:
- Date column converted to date format.
- change_qty already normalize using rule positive when reason column value is "Restock" or "Return", otherway make it negative.

## Stores Table

In [37]:
stor.head()

   store_id       city       store_type
0  STORE000      Delhi  Warehouse Store
1  STORE001  Ahmedabad             Mall
2  STORE002     Jaipur  Warehouse Store
3  STORE003  Hyderabad      High Street
4  STORE004       Pune      High Street

In [38]:
stor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   store_id    50 non-null     object
 1   city        50 non-null     object
 2   store_type  50 non-null     object
dtypes: object(3)
memory usage: 1.3+ KB

In [39]:
stor.isnull().sum()

store_id      0
city          0
store_type    0
dtype: int64

In [40]:
stor['store_id'].nunique() == len(stor)

True

In [41]:
stor['store_type'].unique()

array(['Warehouse Store', 'Mall', 'High Street'], dtype=object)

In [42]:
stor.duplicated().sum()

0

In [ ]:
# Whitespace check:
(stor == "", " ").sum()

## Warehouse Table

In [43]:
ware.head()

  warehouse_id       city  capacity
0        WH000    Chennai     41284
1        WH001      Delhi     30352
2        WH002  Bangalore     11943
3        WH003       Pune     31562
4        WH004       Pune     48079

In [44]:
ware.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   warehouse_id  10 non-null     object
 1   city          10 non-null     object
 2   capacity      10 non-null     int64
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes

In [ ]:
ware['city'].unique()

In [45]:
ware['warehouse_id'].nunique() == len(ware)

True

In [46]:
ware['capacity'].describe()

count       10.000000
mean     34032.800000
std      13154.688702
min      11943.000000
25%      26899.000000
50%      34125.500000
75%      46380.250000
max      49488.000000
Name: capacity, dtype: float64

In [ ]:
# Invalid Values Check In Capacity

ware = ware[ware['capacity'] > 0]

# Data Cleaning

In [ ]:
## standardizing column names

prod.columns = prod.columns.str.strip().str.lower().str.replace(" ", "_")

ord.columns = ord.columns.str.strip().str.lower().str.replace(" ", "_")

cust.columns = cust.columns.str.strip().str.lower().str.replace(" ", "_")

ord_it.columns = ord_it.columns.str.strip().str.lower().str.replace(" ", "_")

inv.columns = inv.columns.str.strip().str.lower().str.replace(" ", "_")

inv_move.columns = inv_move.columns.str.strip().str.lower().str.replace(" ", "_")

stor =  stor.columns.str.strip().str.lower().str.replace(" ", "_")

ware = ware.columns.str.strip().str.lower().str.replace(" ", "_")

In [ ]:
# Store Table Text Cleaning

stor['city'] = stor['city'].str.strip().str.title()
stor['store_type'] = stor['store_type'].str.strip().str.title()

In [ ]:
# Duplicates Check

stor.duplicated()

In [ ]:
# Remove Duplicates

stor = stor.drop_duplicates()
cust = cust.drop_duplicates()
ord_it = ord_it.drop_duplicates()

## Relationships Checks

In [ ]:
# Store & orders relation check

ord['store_id'].isin(stor['store_id']).all()

In [ ]:
# Warehouse & inventroy relation check

inv['warehouse_id'].isin(ware['warehouse_id']).all()

In [ ]:
# Warehouse & Inventory Movement relation check

inv_move['warehouse_id'].isin(ware['warehouse_id']).all()

In [ ]:
# Removing Invalid Values

ord_it = ord_it[ord_it['quantity'] > 0]

In [ ]:
# Saving Clean CSVs

cust.to_csv("clean_customers.csv", index=False)
prod.to_csv("clean_products.csv", index=False)
ord.to_csv("clean_orders.csv", index=False)
ord_it.to_csv("clean_order_items.csv", index=False)
inv.to_csv("clean_inventory.csv", index=False)
inv_move.to_csv("clean_Inventory_movements.csv", index=False)
stor.to_csv("clean_stores.csv", index=False)
ware.to_csv("clean_warehouses.csv", index=False)