In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df=pd.read_csv('student_mental_health.csv')

print(df)

       Name  Gender  Age Education Level  Screen Time (hrs/day)  \
0     Aarav    Male   15         Class 8                    7.1
1     Meera  Female   25             MSc                    3.3
2    Ishaan    Male   20           BTech                    9.5
3    Aditya    Male   20              BA                   10.8
4     Anika  Female   17        Class 11                    2.8
..      ...     ...  ...             ...                    ...
995    Diya  Female   26              MA                   11.3
996   Aarav    Male   20           BTech                    5.5
997    Myra  Female   15         Class 9                    7.1
998    Myra  Female   20              BA                    4.4
999  Vihaan    Male   23              MA                   10.8

     Sleep Duration (hrs)  Physical Activity (hrs/week) Stress Level  \
0                     8.9                           9.3       Medium
1                     5.0                           0.2       Medium
2                     5.4                           6.2       Medium
3                     5.6                           5.5         High
4                     5.4                           3.1       Medium
..                    ...                           ...          ...
995                   6.8                           9.1       Medium
996                   6.7                           6.8          Low
997                   4.1                           1.9          Low
998                   7.5                           4.5       Medium
999                   7.7                           3.6          Low

    Anxious Before Exams Academic Performance Change
0                     No                        Same
1                     No                        Same
2                     No                        Same
3                    Yes                        Same
4                    Yes                        Same
..                   ...                         ...
995                   No                        Same
996                  Yes                        Same
997                  Yes                    Declined
998                   No                    Improved
999                   No                    Improved

[1000 rows x 10 columns]

In [ ]:
df.shape

(1000, 10)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Name                          1000 non-null   object
 1   Gender                        1000 non-null   object
 2   Age                           1000 non-null   int64
 3   Education Level               1000 non-null   object
 4   Screen Time (hrs/day)         1000 non-null   float64
 5   Sleep Duration (hrs)          1000 non-null   float64
 6   Physical Activity (hrs/week)  1000 non-null   float64
 7   Stress Level                  1000 non-null   object
 8   Anxious Before Exams          1000 non-null   object
 9   Academic Performance Change   1000 non-null   object
dtypes: float64(3), int64(1), object(6)
memory usage: 78.3+ KB

In [8]:
df.describe()

,Age,Screen Time (hrs/day),Sleep Duration (hrs),Physical Activity (hrs/week)
count,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.342000,6.909200,6.450800,5.017600
std,3.459914,2.907106,1.466407,2.930344
min,15.000000,2.000000,4.000000,0.000000
25%,17.000000,4.400000,5.100000,2.600000
50%,20.000000,6.900000,6.500000,5.000000
75%,23.000000,9.500000,7.700000,7.600000
max,26.000000,12.000000,9.000000,10.000000

In [18]:
df.isnull().sum()

Name                            0
Gender                          0
Age                             0
Education Level                 0
Screen Time (hrs/day)           0
Sleep Duration (hrs)            0
Physical Activity (hrs/week)    0
Stress Level                    0
Anxious Before Exams            0
Academic Performance Change     0
dtype: int64

In [19]:
df.nunique()

Name                             30
Gender                            3
Age                              12
Education Level                  11
Screen Time (hrs/day)           101
Sleep Duration (hrs)             51
Physical Activity (hrs/week)    101
Stress Level                      3
Anxious Before Exams              2
Academic Performance Change       3
dtype: int64

In [9]:
df.head()

,Name,Gender,Age,Education Level,Screen Time (hrs/day),Sleep Duration (hrs),Physical Activity (hrs/week),Stress Level,Anxious Before Exams,Academic Performance Change
0,Aarav,Male,15,Class 8,7.1,8.9,9.3,Medium,No,Same
1,Meera,Female,25,MSc,3.3,5.0,0.2,Medium,No,Same
2,Ishaan,Male,20,BTech,9.5,5.4,6.2,Medium,No,Same
3,Aditya,Male,20,BA,10.8,5.6,5.5,High,Yes,Same
4,Anika,Female,17,Class 11,2.8,5.4,3.1,Medium,Yes,Same

In [10]:
# Ensuring numeric columns are of correct types
numeric_cols = ['Age', 'Screen Time (hrs/day)', 'Sleep Duration (hrs)', 'Physical Activity (hrs/week)']
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')

In [ ]:
df['Gender'] = df['Gender'].astype('category') # As Category takes less memory

In [13]:
# Clean categorical columns (strip whitespace, unify capitalization)
cat_cols = ['Name', 'Gender', 'Stress Level', 'Anxious Before Exams', 'Academic Performance Change']
df[cat_cols] = df[cat_cols].apply(lambda x: x.str.strip().str.title())

In [ ]:
cat_cols = ['Education Level']
df[cat_cols] = df[cat_cols].apply(lambda x: x.str.strip().str.title())