In [1]:
import pandas as pd
df=pd.read_csv('project_risk_raw_dataset.csv')
df.head()

,Project_ID,Project_Type,Team_Size,Project_Budget_USD,Estimated_Timeline_Months,Complexity_Score,Stakeholder_Count,Methodology_Used,Team_Experience_Level,Past_Similar_Projects,...,Industry_Volatility,Client_Experience_Level,Change_Control_Maturity,Risk_Management_Maturity,Team_Colocation,Documentation_Quality,Project_Start_Month,Current_Phase_Duration_Months,Seasonal_Risk_Factor,Risk_Level
0,PROJ_0001,Construction,32,1526276.55,32,9.70,16,Waterfall,Senior,3,...,Extreme,First-time,Basic,Basic,Fully Colocated,Good,10,5,1.0,High
1,PROJ_0002,Manufacturing,2,390790.15,9,2.72,9,Kanban,Mixed,0,...,Stable,Occasional,Advanced,Formal,Fully Remote,Poor,9,3,1.0,Low
2,PROJ_0003,Manufacturing,2,246674.76,6,2.04,7,Agile,Mixed,1,...,Stable,Regular,NaN,NaN,Hybrid,Good,5,1,1.0,Medium
3,PROJ_0004,IT,12,1427830.63,17,7.54,16,Scrum,Mixed,0,...,Extreme,Strategic,Formal,Basic,Hybrid,Basic,12,6,1.1,High
4,PROJ_0005,Construction,24,1696746.64,24,6.68,17,Hybrid,Junior,0,...,Moderate,Occasional,Basic,NaN,Partially Colocated,Basic,9,6,1.0,High

In [2]:
## Summary of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 51 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Project_ID                       4000 non-null   object
 1   Project_Type                     4000 non-null   object
 2   Team_Size                        4000 non-null   int64
 3   Project_Budget_USD               4000 non-null   float64
 4   Estimated_Timeline_Months        4000 non-null   int64
 5   Complexity_Score                 4000 non-null   float64
 6   Stakeholder_Count                4000 non-null   int64
 7   Methodology_Used                 4000 non-null   object
 8   Team_Experience_Level            4000 non-null   object
 9   Past_Similar_Projects            4000 non-null   int64
 10  External_Dependencies_Count      4000 non-null   int64
 11  Change_Request_Frequency         4000 non-null   float64
 12  Project_Phase                    4000 non-null   object
 13  Requirement_Stability            4000 non-null   object
 14  Team_Turnover_Rate               4000 non-null   float64
 15  Vendor_Reliability_Score         4000 non-null   float64
 16  Historical_Risk_Incidents        4000 non-null   int64
 17  Communication_Frequency          4000 non-null   float64
 18  Regulatory_Compliance_Level      4000 non-null   object
 19  Technology_Familiarity           4000 non-null   object
 20  Geographical_Distribution        4000 non-null   int64
 21  Stakeholder_Engagement_Level     4000 non-null   object
 22  Schedule_Pressure                4000 non-null   float64
 23  Budget_Utilization_Rate          4000 non-null   float64
 24  Executive_Sponsorship            4000 non-null   object
 25  Funding_Source                   4000 non-null   object
 26  Market_Volatility                4000 non-null   float64
 27  Integration_Complexity           4000 non-null   float64
 28  Resource_Availability            4000 non-null   float64
 29  Priority_Level                   4000 non-null   object
 30  Organizational_Change_Frequency  4000 non-null   float64
 31  Cross_Functional_Dependencies    4000 non-null   int64
 32  Previous_Delivery_Success_Rate   4000 non-null   float64
 33  Technical_Debt_Level             4000 non-null   float64
 34  Project_Manager_Experience       4000 non-null   object
 35  Org_Process_Maturity             4000 non-null   object
 36  Data_Security_Requirements       4000 non-null   object
 37  Key_Stakeholder_Availability     4000 non-null   object
 38  Tech_Environment_Stability       1381 non-null   object
 39  Contract_Type                    4000 non-null   object
 40  Resource_Contention_Level        4000 non-null   object
 41  Industry_Volatility              4000 non-null   object
 42  Client_Experience_Level          4000 non-null   object
 43  Change_Control_Maturity          3220 non-null   object
 44  Risk_Management_Maturity         3209 non-null   object
 45  Team_Colocation                  4000 non-null   object
 46  Documentation_Quality            4000 non-null   object
 47  Project_Start_Month              4000 non-null   int64
 48  Current_Phase_Duration_Months    4000 non-null   int64
 49  Seasonal_Risk_Factor             4000 non-null   float64
 50  Risk_Level                       4000 non-null   object
dtypes: float64(15), int64(10), object(26)
memory usage: 1.6+ MB

In [3]:
## descriptive summary of the dataset
df.describe()

,Team_Size,Project_Budget_USD,Estimated_Timeline_Months,Complexity_Score,Stakeholder_Count,Past_Similar_Projects,External_Dependencies_Count,Change_Request_Frequency,Team_Turnover_Rate,Vendor_Reliability_Score,...,Market_Volatility,Integration_Complexity,Resource_Availability,Organizational_Change_Frequency,Cross_Functional_Dependencies,Previous_Delivery_Success_Rate,Technical_Debt_Level,Project_Start_Month,Current_Phase_Duration_Months,Seasonal_Risk_Factor
count,4000.000000,4.000000e+03,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,...,4000.00000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.00000,4000.000000,4000.000000,4000.000000
mean,15.388250,1.143032e+06,17.147750,6.192525,11.130500,1.973750,3.127750,1.638080,0.292725,0.712087,...,0.49716,5.573585,0.651695,1.212215,3.549250,0.750437,0.17544,6.492500,4.074500,1.011325
std,9.220969,5.908781e+05,6.926609,2.212538,4.425875,1.750093,1.609216,1.170451,0.166546,0.163418,...,0.28702,2.606654,0.201163,0.969191,2.320004,0.143712,0.29682,3.476416,2.883926,0.031694
min,2.000000,1.593555e+05,2.000000,1.620000,2.000000,0.000000,0.000000,0.010000,0.000000,0.090000,...,0.00000,1.000000,0.300000,0.000000,0.000000,0.150000,0.00000,1.000000,1.000000,1.000000
25%,9.000000,6.925329e+05,12.000000,4.460000,8.000000,1.000000,2.000000,0.760000,0.160000,0.600000,...,0.25000,3.317500,0.480000,0.500000,2.000000,0.660000,0.00000,4.000000,2.000000,1.000000
50%,13.000000,1.007472e+06,17.000000,6.015000,10.000000,2.000000,3.000000,1.370000,0.270000,0.730000,...,0.50000,5.600000,0.650000,0.960000,4.000000,0.770000,0.00000,7.000000,3.000000,1.000000
75%,20.000000,1.475870e+06,22.000000,7.862500,14.000000,3.000000,4.000000,2.230000,0.400000,0.840000,...,0.74000,7.860000,0.820000,1.660000,6.000000,0.860000,0.28000,10.000000,6.000000,1.000000
max,50.000000,3.768354e+06,36.000000,10.000000,29.000000,10.000000,7.000000,8.840000,0.850000,1.000000,...,1.00000,10.000000,1.000000,8.230000,7.000000,0.990000,1.00000,12.000000,17.000000,1.100000

In [4]:
df.shape

(4000, 51)

In [8]:
## Missing values in the dataset

df.isnull().sum()

Project_ID                            0
Project_Type                          0
Team_Size                             0
Project_Budget_USD                    0
Estimated_Timeline_Months             0
Complexity_Score                      0
Stakeholder_Count                     0
Methodology_Used                      0
Team_Experience_Level                 0
Past_Similar_Projects                 0
External_Dependencies_Count           0
Change_Request_Frequency              0
Project_Phase                         0
Requirement_Stability                 0
Team_Turnover_Rate                    0
Vendor_Reliability_Score              0
Historical_Risk_Incidents             0
Communication_Frequency               0
Regulatory_Compliance_Level           0
Technology_Familiarity                0
Geographical_Distribution             0
Stakeholder_Engagement_Level          0
Schedule_Pressure                     0
Budget_Utilization_Rate               0
Executive_Sponsorship                 0
Funding_Source                        0
Market_Volatility                     0
Integration_Complexity                0
Resource_Availability                 0
Priority_Level                        0
Organizational_Change_Frequency       0
Cross_Functional_Dependencies         0
Previous_Delivery_Success_Rate        0
Technical_Debt_Level                  0
Project_Manager_Experience            0
Org_Process_Maturity                  0
Data_Security_Requirements            0
Key_Stakeholder_Availability          0
Tech_Environment_Stability         2619
Contract_Type                         0
Resource_Contention_Level             0
Industry_Volatility                   0
Client_Experience_Level               0
Change_Control_Maturity             780
Risk_Management_Maturity            791
Team_Colocation                       0
Documentation_Quality                 0
Project_Start_Month                   0
Current_Phase_Duration_Months         0
Seasonal_Risk_Factor                  0
Risk_Level                            0
dtype: int64

In [9]:
## Duplicate records
df[df.duplicated()]

Empty DataFrame
Columns: [Project_ID, Project_Type, Team_Size, Project_Budget_USD, Estimated_Timeline_Months, Complexity_Score, Stakeholder_Count, Methodology_Used, Team_Experience_Level, Past_Similar_Projects, External_Dependencies_Count, Change_Request_Frequency, Project_Phase, Requirement_Stability, Team_Turnover_Rate, Vendor_Reliability_Score, Historical_Risk_Incidents, Communication_Frequency, Regulatory_Compliance_Level, Technology_Familiarity, Geographical_Distribution, Stakeholder_Engagement_Level, Schedule_Pressure, Budget_Utilization_Rate, Executive_Sponsorship, Funding_Source, Market_Volatility, Integration_Complexity, Resource_Availability, Priority_Level, Organizational_Change_Frequency, Cross_Functional_Dependencies, Previous_Delivery_Success_Rate, Technical_Debt_Level, Project_Manager_Experience, Org_Process_Maturity, Data_Security_Requirements, Key_Stakeholder_Availability, Tech_Environment_Stability, Contract_Type, Resource_Contention_Level, Industry_Volatility, Client_Experience_Level, Change_Control_Maturity, Risk_Management_Maturity, Team_Colocation, Documentation_Quality, Project_Start_Month, Current_Phase_Duration_Months, Seasonal_Risk_Factor, Risk_Level]
Index: []

[0 rows x 51 columns]

In [5]:
## List down all the columns names
df.columns

Index(['Project_ID', 'Project_Type', 'Team_Size', 'Project_Budget_USD',
       'Estimated_Timeline_Months', 'Complexity_Score', 'Stakeholder_Count',
       'Methodology_Used', 'Team_Experience_Level', 'Past_Similar_Projects',
       'External_Dependencies_Count', 'Change_Request_Frequency',
       'Project_Phase', 'Requirement_Stability', 'Team_Turnover_Rate',
       'Vendor_Reliability_Score', 'Historical_Risk_Incidents',
       'Communication_Frequency', 'Regulatory_Compliance_Level',
       'Technology_Familiarity', 'Geographical_Distribution',
       'Stakeholder_Engagement_Level', 'Schedule_Pressure',
       'Budget_Utilization_Rate', 'Executive_Sponsorship', 'Funding_Source',
       'Market_Volatility', 'Integration_Complexity', 'Resource_Availability',
       'Priority_Level', 'Organizational_Change_Frequency',
       'Cross_Functional_Dependencies', 'Previous_Delivery_Success_Rate',
       'Technical_Debt_Level', 'Project_Manager_Experience',
       'Org_Process_Maturity', 'Data_Security_Requirements',
       'Key_Stakeholder_Availability', 'Tech_Environment_Stability',
       'Contract_Type', 'Resource_Contention_Level', 'Industry_Volatility',
       'Client_Experience_Level', 'Change_Control_Maturity',
       'Risk_Management_Maturity', 'Team_Colocation', 'Documentation_Quality',
       'Project_Start_Month', 'Current_Phase_Duration_Months',
       'Seasonal_Risk_Factor', 'Risk_Level'],
      dtype='object')

In [7]:
df['Project_Type'].unique()

array(['Construction', 'Manufacturing', 'IT', 'R&D', 'Healthcare',
       'Marketing'], dtype=object)

In [10]:
df['Team_Size'].unique()

array([32,  2, 12, 24, 13,  9, 37, 41, 15, 14, 11, 17,  5,  8, 31,  6, 25,
       10, 30, 21, 20, 33,  4, 26, 16, 35, 19, 22,  7, 38, 23, 28, 27, 18,
       46,  3, 40, 47, 29, 34, 36, 44, 45, 50, 43, 42, 48, 49, 39],
      dtype=int64)

In [11]:
df['Team_Experience_Level'].unique()

array(['Senior', 'Mixed', 'Junior', 'Expert'], dtype=object)

In [ ]:
df['Team_Size'].unique()